Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('1','Bogotá');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('10','Cali');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('9','Villavicencio');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('7','Chia');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('8','Choachi');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('6','Sopo');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('4','Aguazul');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('5','Yopal');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('3','Inirida');
Insert into CiUDAD (ID_CIUDAD,NOMBRE_CIUDAD) values ('2','Soacha');


Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('1','1','Santa Isabel','2');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('2','2','Sevilla','1');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('3','3','Fragua','2');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('4','1','La Libertad','2');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('5','2','La Aurora','1');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('6','3','Rionegro','3');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('7','1','Olarte','1');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('8','2','Marly','4');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('9','1','Ciudad Salitre','4');
Insert into BARRIO (ID_BARRIO,ID_CIUDAD,NOMBRE_BARRIO,ESTRATO) values ('10','1','La Campiña','3');


Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('1','1','48000000','Centro    ','57','13   ',null,null,'32   ','12','Casa azul','1','1','3',null,null,null,null,null,null,null);
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('2','1','81000000','Oriente   ','50','22   ',null,null,'7','18','Casa 2 pisos con balcon','2','3','2',null,null,null,null,null,null,null);
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('3','1','76000000','Norte     ','63','120  ',null,null,'9','24','Casa 5 pisos','2','2','5',null,null,null,null,null,null,null);
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('4','2','180000000','Occidente ','45','24   ',null,null,'89   ','45','Apartamento conjunto cerrado','2','4','1','Rosita del campo','4302',null,null,null,null,null);
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('7','3','5000000','Rural     ','104',null,null,null,null,null,'Lote zona rural bonito','1','1','1',null,null,'Ninguna',null,null,'Via al llano','58');
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('8','3','6000000','Vereda    ','70',null,null,null,null,null,'Lote zona rural cosechable','1','9','1',null,null,'Ninguna',null,null,'Via al coco','2');
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('9','3','6800000','Municipio ','73','2    ',null,null,'13   ','12','Lote zona residencial','2','9','1',null,null,'N/A',null,null,null,null);
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('10','4','850000000','Carretera ','1024',null,null,null,null,null,'Hacienda lujosa','1','9','1',null,null,null,'Ninguna','65721','Via Caño Limon','9');
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('6','2','123009440','NorOcc    ','52','Av 5 ',null,'54',null,'56','Apartamento con balcon y tres habitaciones','2','8','1','Villa Constanza','4102',null,null,null,null,null);
Insert into INMUEBLE (ID_INMUEBLE,TIPO_INMUEBLE,VALOR_INMUEBLE,ZONA_INMUEBLE,DIMENSION_INMUEBLE,CALLE,TRANSVERSAL,DIAGONAL,CARRERA,NUMERO_CASA,DESCRIPCION_INMUEBLE,ESTADO_INMUEBLE,ID_BARRIO,NUMERO_PISOS,NOMBRE_CONJUNTO,NUMERO_APTO,LICENCIA,RENSTRICCIONES_CONSTRUCCION,MATRICULA_INMOBILIARIA,VIA,KILOMERO) values ('5','2','13000000','Sur       ','70','2 sur','34',null,null,'12 ','Apartamento con 2 baños','1','4','1','Valles del comienzo','2801',null,null,null,null,null);

Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('1','1','John Jose Meregildo','jmeregildo@gmail.com','1000000','1',null,null,null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('2','1','Cristian Meluk','cmeluk@gmail.com','1500000','2',null,null,null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('3','1','Mauricio Rodas','mrodas@gmail.com','5230000','1',null,null,null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('4','1','Jairo Velez','jvelez@gmail.com','50000','1',null,null,null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('5','2','Vanessa Pote','vpote@gmail.com',null,'3','Buena','HelloWorld',null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('6','2','Sofia Muller','smuller@gmail.com',null,'3','Regular. La cliente es muy criticona','JabonDeCoco',null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('7','2','Hildebrando Castano','hcastano@gmail.com',null,'4','Excelente cliente, atento.',null,null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('8','2','Sergio Vasquez','svasquez@gmail.com',null,'2','Entablar una conversacion es dificil','ssservasquezzz',null,null);
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('9','3','Diana Turbay','dturbay@gmail.com',null,null,null,null,'Modificar la data de la base de datos, venta y compra de inmuebles','diana#147');
Insert into PERSONA (ID_PERSONA,TIPO_PERSONA,NOMBRE,EMAIL,VR_COMISION,CALIFICACION_CLIENTE,EXPERIENCIA,CONTRASENA,PRIVILEGIOS,CONTRASENA_ADMIN) values ('10','3','Dario Benitez','dbenitez@gmail.com',null,null,null,null,'Acceder a toda la informacion correspondiente a la BD','maxelperroAzul');



insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (1, 5, 'Inmobiliaria muy confiable, personal idoneo para la funcion');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (2, 6, 'Una experiencia unica con la gente mas experta en el tema');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (3, 7, 'Los mejores en fincaraiz!!');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (4, 8, 'Super confiable');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (5, 5, 'Excelente servicio');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (6, 8, 'Precios a la medida del bolsillo');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (7, 6, 'La mejor base de datos ');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (8, 7, 'Calidad y economia garantizada');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (9, 5, 'Las mejores casas en su catalogo');
insert into COMENTARIO (ID_COMENTARIO, ID_PERSONA, COMENTARIO) values (10, 8, 'La mejor experiencia en compra de finca raiz');

Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('1','4');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('2','5');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('3','6');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('4','2');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('5','7');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('5','8');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('6','3');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('7','1');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('8','3');
Insert into REL_COMI_INM (ID_PERSONA,ID_INMUEBLE) values ('8','7');

Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('1',to_date('23/07/17','DD/MM/RR'),'9');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('2',to_date('22/02/19','DD/MM/RR'),'3');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('3',to_date('25/02/18','DD/MM/RR'),'6');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('4',to_date('24/11/16','DD/MM/RR'),'2');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('5',to_date('22/09/18','DD/MM/RR'),'10');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('6',to_date('20/05/15','DD/MM/RR'),'8');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('7',to_date('04/08/18','DD/MM/RR'),'1');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('8',to_date('08/10/17','DD/MM/RR'),'4');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('9',to_date('05/03/17','DD/MM/RR'),'7');
Insert into COMPRA (ID_COMPRA,FECHA_COMPRA,ID_INMUEBLE) values ('10',to_date('01/10/16','DD/MM/RR'),'5');



Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('10',to_date('27/01/18','DD/MM/RR'),'1');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('9',to_date('27/09/17','DD/MM/RR'),'2');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('8',to_date('06/11/15','DD/MM/RR'),'3');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('7',to_date('23/06/12','DD/MM/RR'),'1');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('6',to_date('15/09/19','DD/MM/RR'),'2');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('5',to_date('26/08/16','DD/MM/RR'),'3');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('4',to_date('01/01/19','DD/MM/RR'),'1');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('3',to_date('29/04/10','DD/MM/RR'),'2');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('2',to_date('21/10/14','DD/MM/RR'),'3');
Insert into PROCESOS_DERECHOS_INMUEBLE(ID_DERECHOS,FECHA_ADQUISICION,ID_INMUEBLE) values ('1',to_date('24/04/15','DD/MM/RR'),'1');





Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('10','200','300000000','Mazuren','6','2','2','10');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('9','35','90000000','La Capilla','8','1','3','8');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('7','123','500000000','Unicentro','10','2','1','7');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('6','80','150000000','Casa Blanca','7','1','3','5');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('4','120','250000000','San Bernardo','15','1','5','4');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('2','20','90000000','Hayuelos','3','2','1','3');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('1','50','120000000','San Francisco','10','1','4','1');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('8','30','55000001','Meisen','4','3','2','8');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('5','30','50000000','Alborizadora Alta','3','3','2','6');
Insert into REQUERIMIENTO (ID_REQUERIMIENTO,R_DIMENSION_INMUEBLE,R_VALOR_MAX_INMUEBLE,R_ZONA_INMUEBLE,R_NUMERO_HABITACIONES,R_TIPO_INMUEBLE,R_NUMERO_PISOS,ID_PERSONA) values ('3','100','60000000','San Rafael','1','4','1','2');

Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('1',to_date('29/05/19','DD/MM/RR'),to_date('31/03/19','DD/MM/RR'),'2','12563','5','10');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('2',to_date('16/03/19','DD/MM/RR'),to_date('01/01/19','DD/MM/RR'),'3','12750','6','9');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('3',to_date('17/07/19','DD/MM/RR'),to_date('30/05/19','DD/MM/RR'),'1','86867','6','9');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('4',to_date('22/12/19','DD/MM/RR'),to_date('26/05/19','DD/MM/RR'),'2','17000','5','10');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('5',to_date('02/06/17','DD/MM/RR'),to_date('24/04/17','DD/MM/RR'),'1','159','5','9');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('6',to_date('10/12/17','DD/MM/RR'),to_date('20/10/17','DD/MM/RR'),'3','31230','8','10');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('7',to_date('11/03/17','DD/MM/RR'),to_date('16/01/17','DD/MM/RR'),'2','173000','5','10');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('8',to_date('01/06/17','DD/MM/RR'),to_date('06/04/17','DD/MM/RR'),'2','22000','6','9');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('9',to_date('21/10/18','DD/MM/RR'),to_date('10/03/18','DD/MM/RR'),'2','10000','5','9');
Insert into SERVICIO_A_PAGAR (ID_FACTURA,FECHA_A_PAGAR,FECHA_VENCIMIENTO,TIPO_RECIBO,VALOR_A_PAGAR,ID_INMUEBLE,ID_PERSONA) values ('10',to_date('04/05/19','DD/MM/RR'),to_date('04/04/19','DD/MM/RR'),'2','50000','4','9');


Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('1','10','542000');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('2','9','7762330');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('3','8','623123');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('4','7','123123');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('5','6','8885673');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('6','5','1009632');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('7','4','7328633');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('8','3','6778912');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('9','2','1271290');
Insert into VALOR_ZONA (ID_ZONA,ID_BARRIO,VALOR_METRO_CUADRADO) values ('10','1','1267898');



Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('1',to_date('25/10/14','DD/MM/RR'),'2');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('5',to_date('05/04/18','DD/MM/RR'),'7');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('7',to_date('10/01/16','DD/MM/RR'),'8');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('8',to_date('01/10/17','DD/MM/RR'),'6');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('9',to_date('01/11/18','DD/MM/RR'),'5');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('10',to_date('02/07/16','DD/MM/RR'),'9');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('3',to_date('14/05/18','DD/MM/RR'),'3');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('4',to_date('30/04/19','DD/MM/RR'),'10');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('6',to_date('07/02/19','DD/MM/RR'),'4');
Insert into VENTA (ID_VENTA,FECHA_VENTA,ID_INMUEBLE) values ('2',to_date('02/03/19','DD/MM/RR'),'1');
